# Form implementation generated from reading ui file 'OWO.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GetID(object):
    def setupUi(self, GetID):
        GetID.setObjectName("GetID")
        GetID.setEnabled(True)
        GetID.resize(400, 200)
        GetID.setMinimumSize(QtCore.QSize(400, 200))
        GetID.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("华康方圆体W7(P)")
        font.setPointSize(12)
        GetID.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("-0.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        GetID.setWindowIcon(icon)
        GetID.setAutoFillBackground(False)
        GetID.setStyleSheet("background-image: url(:/エレン・ミラ・メイザース/background.png);")
        self.Main = QtWidgets.QGroupBox(parent=GetID)
        self.Main.setGeometry(QtCore.QRect(-10, -10, 410, 220))
        self.Main.setMinimumSize(QtCore.QSize(410, 220))
        self.Main.setMaximumSize(QtCore.QSize(410, 220))
        self.Main.setStyleSheet("font: 12pt \"华康方圆体W7\";")
        self.Main.setTitle("")
        self.Main.setObjectName("Main")
        self.label = QtWidgets.QLabel(parent=self.Main)
        self.label.setGeometry(QtCore.QRect(50, 130, 41, 21))
        self.label.setMinimumSize(QtCore.QSize(41, 21))
        self.label.setMaximumSize(QtCore.QSize(41, 21))
        self.label.setObjectName("label")
        self.showready = QtWidgets.QLabel(parent=self.Main)
        self.showready.setGeometry(QtCore.QRect(90, 170, 200, 21))
        self.showready.setMinimumSize(QtCore.QSize(200, 21))
        self.showready.setMaximumSize(QtCore.QSize(41, 21))
        self.showready.setStyleSheet("background-image: url(:/エレン・ミラ・メイザース/Nll.png);")
        self.showready.setObjectName("showready")
        self.showget = QtWidgets.QLabel(parent=self.Main)
        self.showget.setGeometry(QtCore.QRect(90, 130, 200, 21))
        self.showget.setMinimumSize(QtCore.QSize(200, 21))
        self.showget.setMaximumSize(QtCore.QSize(41, 21))
        self.showget.setStyleSheet("background-image: url(:/エレン・ミラ・メイザース/Nll.png);")
        self.showget.setObjectName("showget")
        self.label_2 = QtWidgets.QLabel(parent=self.Main)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 41, 21))
        self.label_2.setMinimumSize(QtCore.QSize(41, 21))
        self.label_2.setMaximumSize(QtCore.QSize(41, 21))
        self.label_2.setObjectName("label_2")
        self.overcopy = QtWidgets.QListView(parent=self.Main)
        self.overcopy.setGeometry(QtCore.QRect(20, 20, 256, 91))
        self.overcopy.setMinimumSize(QtCore.QSize(256, 91))
        self.overcopy.setMaximumSize(QtCore.QSize(256, 91))
        self.overcopy.setObjectName("overcopy")
        self.getready = QtWidgets.QPushButton(parent=self.Main)
        self.getready.setGeometry(QtCore.QRect(20, 170, 21, 21))
        self.getready.setMinimumSize(QtCore.QSize(21, 21))
        self.getready.setMaximumSize(QtCore.QSize(21, 21))
        self.getready.setText("")
        self.getready.setObjectName("getready")
        self.Get = QtWidgets.QPushButton(parent=self.Main)
        self.Get.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.Get.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Get.setObjectName("Get")

        self.retranslateUi(GetID)
        QtCore.QMetaObject.connectSlotsByName(GetID)

    def retranslateUi(self, GetID):
        _translate = QtCore.QCoreApplication.translate
        GetID.setWindowTitle(_translate("GetID", "网易云点歌指令生成器"))
        self.label.setToolTip(_translate("GetID", "<html><head/><body><p>已存储至剪贴板</p></body></html>"))
        self.label.setText(_translate("GetID", "指令:"))
        self.showready.setText(_translate("GetID", "点歌 1957440334"))
        self.showget.setText(_translate("GetID", "点歌 1957440334"))
        self.label_2.setToolTip(_translate("GetID", "<html><head/><body><p>已存储过该歌曲的点歌指令</p></body></html>"))
        self.label_2.setText(_translate("GetID", "排除:"))
        self.overcopy.setToolTip(_translate("GetID", "<html><head/><body><p>已经被排除的指令列表</p></body></html>"))
        self.getready.setToolTip(_translate("GetID", "<html><head/><body><p>复制该指令</p></body></html>"))
        self.Get.setToolTip(_translate("GetID", "<html><head/><body><p>解析剪贴板中的歌曲链接</p></body></html>"))
        self.Get.setText(_translate("GetID", "获取"))
